
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%	
% Uses UNC's Copyright and Permission Notice:	
% COPYRIGHT AND PERMISSION NOTICE	
% UNC Software:  << Liver_glycogen_model >>
% Copyright (C) 2009 The University of North Carolina at Chapel
% All rights reserved.
% The University of North Carolina at Chapel Hill (?UNC?) and the
% developers (?Developers?) of << Liver_glycogen_model>> (?Software?) give
% recipient (?Recipient?) and Recipient?s Institution (?Institution?)
% permission to use and copy the software in source and binary forms, with
% or without modification for non-commercial purposes only provided that
% the following conditions are met:
% 1)	All copies of Software in binary form and/or source code, related
% documentation and/or other materials provided with the Software must
% reproduce and retain the above copyright notice, this list of conditions
% and the following disclaimer.    
% 2)	Recipient and Institution shall not distribute Software to any
% third parties. 
% 3)	The Software is provided ?As Is.? The Developers can not guarantee
% the provision of technical support or consultation for the Software. The
% Developers may provide a location on a UNC Web Site for Recipients to
% post comments, questions, and suggestions at some time in the future.
% Recipient may provide the Developers with feedback on the use of the
% Software in their research at that time.  The Developers and UNC are
% permitted to use any information Recipient provides in making changes to
% the Software.        
% 4)	Recipient acknowledges that the Developers, UNC and its licensees
% may develop modifications to Software that may be substantially similar
% to Recipient?s modifications of Software, and that the Developers, UNC
% and its licensees shall not be constrained in any way by Recipient in
% UNC?s or its licensees? use or management of such modifications.
% Recipient acknowledges the right of the Developers and UNC to prepare and
% publish modifications to Software that may be substantially similar or
% functionally equivalent to your modifications and improvements, and if
% Recipient or Institution obtains patent protection for any modification
% or improvement to Software, Recipient and Institution agree not to allege
% or enjoin infringement of their patent by the Developers, UNC or any of
% UNC?s licensees obtaining modifications or improvements to Software from
% the UNC or the Developers.            
% 5)	Recipient and Developer will acknowledge in their respective
% publications the contributions made to each other?s research involving or
% based on the Software. The current citations for Software are:
% <<<PENDING LIST>>>	
% 6)	Any party desiring a license to use the Software for commercial
% purposes shall contact The Office of Technology Development at UNC at
% 919-966-3929.  
% THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS, CONTRIBUTORS, AND THE
% UNIVERSITY OF NORTH CAROLINA AT CHAPEL HILL "AS IS" AND ANY EXPRESS OR
% IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
% OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
% IN NO EVENT SHALL THE COPYRIGHT OWNER, CONTRIBUTORS OR THE UNIVERSITY OF
% NORTH CAROLINA AT CHAPEL HILL BE LIABLE FOR ANY DIRECT, INDIRECT,
% INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
% NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
% DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
% THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
% (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
% THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.          
%
%
% Description:  
% Generate figures for GSa and GPa after external glucose
% supply re-enters blood stream at two different times: t1=250 mins in fed
% livers and t2 = 1200 mins in fasted livers.  Figure 1: GSa and GPa vs.
% time in fasted liver. Figure 2: glycogen concentraion vs. time in fasted
% liver. Figure 3: GSa and GPa vs. time in fed liver. Figure 4: glycogen
% concentraion vs. time in fed liver. Function is called by runmain.m. Data
% source is in ./results, generated by runmain.m.  
%%%%%%%



function plot_conc(conc)

% Fed liver
close all;
tend = 20; %finish time of the simulation
pt = 70 /1000; % mM total Glycogen Phosphorylase
st = 3 /1000; % mM total Glycogen synthase
tskip = 24; % step size for markers 
   
for i=1:size(conc)
    chartemp = num2str(conc(i));
    chartemp(find(chartemp=='.')) = 'p';
    filename = ['./results/y_fasted_',chartemp];

     load(filename);
     clear(chartemp);
     chartemp=['y_p',num2str(i)];
     eval([chartemp '=y']);
     chartemp=['t_p',num2str(i)];
     eval([chartemp '=t']);
end
clc
display('fasted liver data loaded, plotting...');
     

tstart = 1200; % fasting time in fasted livers

figure(1);
subplot(221)
plot(t_p1(1:6:6)-tstart,y_p1(1:6:6,42)/st,'-ks','MarkerEdgeColor','k', 'MarkerFaceColor','k','MarkerSize',4)
hold on; 
plot(t_p1(1:6:6)-tstart,y_p1(1:6:6,41)/pt,'-ko','MarkerEdgeColor','k', 'MarkerFaceColor','w','MarkerSize',4);
plot(t_p1(1:tskip:end)-tstart,y_p1(1:tskip:end,42)/st,'ks','MarkerEdgeColor','k', 'MarkerFaceColor','k','MarkerSize',4)
plot(t_p1(1:tskip:end)-tstart,y_p1(1:tskip:end,41)/pt,'ko','MarkerEdgeColor','k', 'MarkerFaceColor','w','MarkerSize',4);
plot(t_p1-tstart,y_p1(:,41)/pt,'k')
plot(t_p1-tstart,y_p1(:,42)/st,'k');
legend('GSa','GPa')

xlabel('t(min)')
ylabel('Active enzyme percentage');
title(['Fasted: gluc\_input = ',num2str(conc(1)),' mM/min']);
set(gca,'xtick',[0 2 4 6 8 10 12 14 16 18 20]);
axis([0 tend 0 1]);

subplot(222)
plot(t_p2(1:2:end)-tstart,y_p2(1:2:end,41)/pt,'k')
hold on; plot(t_p2(1:2:end)-tstart,y_p2(1:2:end,42)/st,'k');

hold on; plot(t_p2(1:tskip:end)-tstart,y_p2(1:tskip:end,42)/st,'ks','MarkerEdgeColor','k', 'MarkerFaceColor','k','MarkerSize',4)
hold on; plot(t_p2(1:tskip:end)-tstart,y_p2(1:tskip:end,41)/pt,'ko','MarkerEdgeColor','k', 'MarkerFaceColor','w','MarkerSize',4);
axis([0 tend 0 1])
xlabel('t(min)')
ylabel('Active enzyme percentage');
title(['Fasted: gluc\_input = ',num2str(conc(2)),' mM/min']);
set(gca,'xtick',[0 2 4 6 8 10 12 14 16 18 20]);

subplot(223)
plot(t_p3-tstart,y_p3(:,41)/pt,'k')
hold on; plot(t_p3-tstart,y_p3(:,42)/st,'k');

hold on; plot(t_p3(1:tskip:end)-tstart,y_p3(1:tskip:end,42)/st,'ks','MarkerEdgeColor','k', 'MarkerFaceColor','k','MarkerSize',4)
hold on; plot(t_p3(1:tskip:end)-tstart,y_p3(1:tskip:end,41)/pt,'ko','MarkerEdgeColor','k', 'MarkerFaceColor','w','MarkerSize',4);
axis([0 tend 0 1])
xlabel('t(min)')
ylabel('Active enzyme percentage');
title(['Fasted: gluc\_input = ',num2str(conc(3)),' mM/min']);
set(gca,'xtick',[0 2 4 6 8 10 12 14 16 18 20]);

subplot(224)
plot(t_p4-tstart,y_p4(:,41)/pt,'k')
hold on; plot(t_p4-tstart,y_p4(:,42)/st,'k');

hold on; plot(t_p4(1:tskip:end)-tstart,y_p4(1:tskip:end,42)/st,'ks','MarkerEdgeColor','k', 'MarkerFaceColor','k','MarkerSize',4)
hold on; plot(t_p4(1:tskip:end)-tstart,y_p4(1:tskip:end,41)/pt,'ko','MarkerEdgeColor','k', 'MarkerFaceColor','w','MarkerSize',4);
axis([0 tend 0 1])
xlabel('t(min)')
ylabel('Active enzyme percentage');
title(['Fasted: gluc\_input = ',num2str(conc(4)),' mM/min']);
set(gca,'xtick',[0 2 4 6 8 10 12 14 16 18 20]);



figure(2);
subplot(221)
plot(t_p1(1:tskip:end)-tstart,y_p1(1:tskip:end,3),'ks','MarkerEdgeColor','k', 'MarkerFaceColor','k','MarkerSize',4)
hold on;
plot(t_p1-tstart,y_p1(:,3),'k')
xlabel('t(min)')
ylabel('[glycogen]');
title(['Fasted: gluc\_input = ',num2str(conc(1)),' mM/min']);
set(gca,'xtick',[0 2 4 6 8 10 12 14 16 18 20]);
axis([0 tend 0 3])

subplot(222)
plot(t_p2(1:tskip:end)-tstart,y_p2(1:tskip:end,3),'ks','MarkerEdgeColor','k', 'MarkerFaceColor','k','MarkerSize',4)
hold on;
plot(t_p2-tstart,y_p2(:,3),'k')

axis([0 tend 0 3])
xlabel('t(min)')
ylabel('[glycogen]');
title(['Fasted: gluc\_input = ',num2str(conc(2)),' mM/min']);
set(gca,'xtick',[0 2 4 6 8 10 12 14 16 18 20]);

subplot(223)
plot(t_p3(1:tskip:end)-tstart,y_p3(1:tskip:end,3),'ks','MarkerEdgeColor','k', 'MarkerFaceColor','k','MarkerSize',4)
hold on;
plot(t_p3-tstart,y_p3(:,3),'k')
axis([0 tend 0 3])
xlabel('t(min)')
ylabel('[glycogen]');
title(['Fasted: gluc\_input = ',num2str(conc(3)),' mM/min']);
set(gca,'xtick',[0 2 4 6 8 10 12 14 16 18 20]);

subplot(224)
plot(t_p4(1:tskip:end)-tstart,y_p4(1:tskip:end,3),'ks','MarkerEdgeColor','k', 'MarkerFaceColor','k','MarkerSize',4)
hold on;
plot(t_p4-tstart,y_p4(:,3),'k')
axis([0 tend 0 3])
xlabel('t(min)')
ylabel('[glycogen]');
title(['Fasted: gluc\_input = ',num2str(conc(4)),' mM/min']);
set(gca,'xtick',[0 2 4 6 8 10 12 14 16 18 20]);

s='Y';
reply = input('Continue to fed liver? Y/N [Y]:','s');
if 'Y';
    for i=1:size(conc)
        chartemp = num2str(conc(i));
        chartemp(find(chartemp=='.')) = 'p';
        filename = ['./results/y_fed_',chartemp];

         load(filename);
         clear(chartemp);
         chartemp=['y_p',num2str(i)];
         eval([chartemp '=y']);
         chartemp=['t_p',num2str(i)];
         eval([chartemp '=t']);
    end
    clc
    display('fed liver data loaded, plotting...');
    
    tstart = 250; % fasting time in fasted livers
    figure(3);
    subplot(221)
    plot(t_p1(1:6:6)-tstart,y_p1(1:6:6,42)/st,'-ks','MarkerEdgeColor','k', 'MarkerFaceColor','k','MarkerSize',4)
    hold on; 
    plot(t_p1(1:6:6)-tstart,y_p1(1:6:6,41)/pt,'-ko','MarkerEdgeColor','k', 'MarkerFaceColor','w','MarkerSize',4);
    plot(t_p1(1:tskip:end)-tstart,y_p1(1:tskip:end,42)/st,'ks','MarkerEdgeColor','k', 'MarkerFaceColor','k','MarkerSize',4)
    plot(t_p1(1:tskip:end)-tstart,y_p1(1:tskip:end,41)/pt,'ko','MarkerEdgeColor','k', 'MarkerFaceColor','w','MarkerSize',4);
    plot(t_p1-tstart,y_p1(:,41)/pt,'k')
    plot(t_p1-tstart,y_p1(:,42)/st,'k');
    legend('GSa','GPa')

    xlabel('t(min)')
    ylabel('Active enzyme percentage');
    title(['Fed: gluc_input = ',num2str(conc(1)),' mM/min']);
    set(gca,'xtick',[0 2 4 6 8 10 12 14 16 18 20]);
    axis([0 tend 0 1])

    subplot(222)
    plot(t_p2(1:2:end)-tstart,y_p2(1:2:end,41)/pt,'k')
    hold on; plot(t_p2(1:2:end)-tstart,y_p2(1:2:end,42)/st,'k');

    hold on; plot(t_p2(1:tskip:end)-tstart,y_p2(1:tskip:end,42)/st,'ks','MarkerEdgeColor','k', 'MarkerFaceColor','k','MarkerSize',4)
    hold on; plot(t_p2(1:tskip:end)-tstart,y_p2(1:tskip:end,41)/pt,'ko','MarkerEdgeColor','k', 'MarkerFaceColor','w','MarkerSize',4);
    axis([0 tend 0 1])
    xlabel('t(min)')
    ylabel('Active enzyme percentage');
    title(['Fed: gluc_input = ',num2str(conc(2)),' mM/min']);
    set(gca,'xtick',[0 2 4 6 8 10 12 14 16 18 20]);

    subplot(223)
    plot(t_p3-tstart,y_p3(:,41)/pt,'k')
    hold on; plot(t_p3-tstart,y_p3(:,42)/st,'k');

    hold on; plot(t_p3(1:tskip:end)-tstart,y_p3(1:tskip:end,42)/st,'ks','MarkerEdgeColor','k', 'MarkerFaceColor','k','MarkerSize',4)
    hold on; plot(t_p3(1:tskip:end)-tstart,y_p3(1:tskip:end,41)/pt,'ko','MarkerEdgeColor','k', 'MarkerFaceColor','w','MarkerSize',4);
    axis([0 tend 0 1])
    xlabel('t(min)')
    ylabel('Active enzyme percentage');
    title(['Fed: gluc_input = ',num2str(conc(3)),' mM/min']);
    set(gca,'xtick',[0 2 4 6 8 10 12 14 16 18 20]);

    subplot(224)
    plot(t_p4-tstart,y_p4(:,41)/pt,'k')
    hold on; plot(t_p4-tstart,y_p4(:,42)/st,'k');

    hold on; plot(t_p4(1:tskip:end)-tstart,y_p4(1:tskip:end,42)/st,'ks','MarkerEdgeColor','k', 'MarkerFaceColor','k','MarkerSize',4)
    hold on; plot(t_p4(1:tskip:end)-tstart,y_p4(1:tskip:end,41)/pt,'ko','MarkerEdgeColor','k', 'MarkerFaceColor','w','MarkerSize',4);
    axis([0 tend 0 1])
    xlabel('t(min)')
    ylabel('Active enzyme percentage');
    title(['Fed: gluc_input = ',num2str(conc(4)),' mM/min']);
    set(gca,'xtick',[0 2 4 6 8 10 12 14 16 18 20]);


    figure(4);
    subplot(221)
    plot(t_p1(1:tskip:end)-tstart,y_p1(1:tskip:end,3),'ks','MarkerEdgeColor','k', 'MarkerFaceColor','k','MarkerSize',4)
    hold on;
    plot(t_p1-tstart,y_p1(:,3),'k')
    xlabel('t(min)')
    ylabel('[glycogen]');
    title(['Fed: gluc\_input = ',num2str(conc(1)),' mM/min']);
     axis([0 tend 89 93])
     set(gca,'xtick',[0 2 4 6 8 10 12 14 16 18 20]);

    subplot(222)
    plot(t_p2(1:tskip:end)-tstart,y_p2(1:tskip:end,3),'ks','MarkerEdgeColor','k', 'MarkerFaceColor','k','MarkerSize',4)
    hold on;
    plot(t_p2-tstart,y_p2(:,3),'k')

      axis([0 tend 89 93])
    xlabel('t(min)')
    ylabel('[glycogen]');
    title(['Fed: gluc\_input = ',num2str(conc(2)),' mM/min']);
    set(gca,'xtick',[0 2 4 6 8 10 12 14 16 18 20]);

    subplot(223)
    plot(t_p3(1:tskip:end)-tstart,y_p3(1:tskip:end,3),'ks','MarkerEdgeColor','k', 'MarkerFaceColor','k','MarkerSize',4)
    hold on;
    plot(t_p3-tstart,y_p3(:,3),'k')
      axis([0 tend 89 93])
    xlabel('t(min)')
    ylabel('[glycogen]');
    title(['Fed: gluc\_input = ',num2str(conc(3)),' mM/min']);
    set(gca,'xtick',[0 2 4 6 8 10 12 14 16 18 20]);

    subplot(224)
    plot(t_p4(1:tskip:end)-tstart,y_p4(1:tskip:end,3),'ks','MarkerEdgeColor','k', 'MarkerFaceColor','k','MarkerSize',4)
    hold on;
    plot(t_p4-tstart,y_p4(:,3),'k')
    axis([0 tend 89 93])
    xlabel('t(min)')
    ylabel('[glycogen]');
    title(['Fed: gluc\_input = ',num2str(conc(4)),' mM/min']);
    set(gca,'xtick',[0 2 4 6 8 10 12 14 16 18 20]);

    
    
     
else 
    return;
end

